-- Enable Row Level Security on all tables

-- Core models
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceAU" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;

-- Contractor models
ALTER TABLE "Contractor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contractor_onboarding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contractor_assessments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contractor_module_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contractor_certifications" ENABLE ROW LEVEL SECURITY;

-- Client models
ALTER TABLE "client_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_properties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_insurance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_onboarding" ENABLE ROW LEVEL SECURITY;

-- Insurance models
ALTER TABLE "InsuranceClaimAU" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InsuranceProvider" ENABLE ROW LEVEL SECURITY;

-- Rating and inspection models
ALTER TABLE "Rating" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inspection_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "damage_areas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inspection_photos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "moisture_readings" ENABLE ROW LEVEL SECURITY;

-- Cost estimate models
ALTER TABLE "cost_estimates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "labor_line_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "material_line_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "equipment_line_items" ENABLE ROW LEVEL SECURITY;

-- Compliance models
ALTER TABLE "compliance_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "report_revisions" ENABLE ROW LEVEL SECURITY;

-- Audit and system models
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LoginAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;

-- CRM models
ALTER TABLE "customer_lifecycle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "opportunities" ENABLE ROW LEVEL SECURITY;

-- Content models
ALTER TABLE "blog_posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "faqs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "case_studies" ENABLE ROW LEVEL SECURITY;

-- Beta program models
ALTER TABLE "beta_programs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "beta_enrollments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "beta_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "beta_nps_surveys" ENABLE ROW LEVEL SECURITY;
