/**
 * RestoreAssist Landing Page — DR-244
 *
 * Client-facing trust signal page explaining how NRPG contractors
 * use RestoreAssist (on-site inspection, reporting & scoping system)
 * to produce professional insurer-ready documentation in the field.
 *
 * SEO: "RestoreAssist", "insurance documentation disaster restoration",
 *       "professional restoration report insurer", "NRPG RestoreAssist"
 *
 * Architecture: DR (this page, client trust signal) →
 *               NRPG contractor dispatched →
 *               RestoreAssist.app (field tool, separate product) →
 *               insurer documentation delivered
 */

import type { Metadata } from 'next';
import Header from '@/components/header';
import Footer from '@/components/footer';
import Link from 'next/link';
import { CheckCircle, FileText, Camera, BarChart2, Shield, ArrowRight, ClipboardList, Zap } from 'lucide-react';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://disasterrecovery.com.au';
const CANONICAL = `${BASE_URL}/restore-assist`;

export const metadata: Metadata = {
  title: 'RestoreAssist — Professional Field Documentation for Insurance Claims | NRPG',
  description:
    'Every NRPG contractor uses RestoreAssist on-site — producing real-time inspection reports, moisture mapping, and scope of works your insurer needs to approve your claim fast. Powered by NRPG.',
  keywords: [
    'RestoreAssist insurance documentation',
    'professional restoration report insurer',
    'NRPG RestoreAssist',
    'disaster restoration field documentation',
    'insurance claim scope of works',
    'IICRC moisture mapping report',
    'water damage insurance documentation Australia',
    'restoration contractor field reporting',
  ],
  alternates: { canonical: CANONICAL },
  openGraph: {
    title: 'RestoreAssist — On-Site Reporting That Gets Claims Approved | NRPG',
    description:
      'NRPG contractors document your damage in real time using RestoreAssist — the professional field system that gives insurers exactly what they need.',
    url: CANONICAL,
    siteName: 'NRPG - Disaster Recovery Australia',
    type: 'website',
    locale: 'en_AU',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'RestoreAssist — On-Site Documentation | NRPG Australia',
    description: 'Real-time inspection reports, moisture mapping, and scope of works — automatically generated by your NRPG contractor on-site.',
  },
  robots: { index: true, follow: true },
};

const SERVICE_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'RestoreAssist — Field Inspection, Reporting & Scoping System',
  description:
    'RestoreAssist is the professional on-site inspection, reporting, and scoping system used by all NRPG contractors. It generates real-time moisture mapping, photographic documentation, and insurance-standard scope of works during every restoration job.',
  provider: {
    '@type': 'Organization',
    name: 'NRPG - National Restoration Partners Guild',
    url: BASE_URL,
  },
  areaServed: { '@type': 'Country', name: 'Australia' },
  url: CANONICAL,
};

const BREADCRUMB_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: BASE_URL },
    { '@type': 'ListItem', position: 2, name: 'RestoreAssist', item: CANONICAL },
  ],
};

const FAQ_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is RestoreAssist?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'RestoreAssist is the professional on-site inspection, reporting, and scoping system used by all NRPG contractors. It generates real-time moisture maps, photographic records, and insurance-standard scope of works documents during every disaster restoration job.',
      },
    },
    {
      '@type': 'Question',
      name: 'How does RestoreAssist help with my insurance claim?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'RestoreAssist produces the professional documentation your insurer needs to assess and approve your claim — including moisture readings, before-and-after photos, equipment logs, and a formal scope of works. This documentation is generated on-site by your NRPG contractor and submitted directly to your insurer, eliminating delays and disputes.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do I need to pay extra for RestoreAssist documentation?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. RestoreAssist documentation is included as a standard part of every NRPG job. It is not an optional extra — every NRPG contractor is required to use RestoreAssist on every job to maintain consistent professional standards.',
      },
    },
  ],
};

// ---------------------------------------------------------------------------
// How it works steps
// ---------------------------------------------------------------------------

const HOW_IT_WORKS = [
  {
    step: '01',
    icon: ClipboardList,
    title: 'You submit a claim through DR',
    description: 'Property owner submits an emergency claim through disasterrecovery.com.au — takes under 3 minutes.',
  },
  {
    step: '02',
    icon: Zap,
    title: 'NRPG contractor dispatched',
    description: 'The nearest certified NRPG contractor is dispatched with RestoreAssist loaded on their field device.',
  },
  {
    step: '03',
    icon: Camera,
    title: 'On-site documentation begins',
    description: 'From the moment they arrive, RestoreAssist captures photos, moisture readings, and damage assessment in real time.',
  },
  {
    step: '04',
    icon: FileText,
    title: 'Scope of works generated',
    description: 'A professional IICRC-standard scope of works is automatically generated from the field data — ready for your insurer.',
  },
  {
    step: '05',
    icon: BarChart2,
    title: 'Daily drying reports',
    description: 'Throughout the job, RestoreAssist logs equipment placements, moisture readings, and drying progress — producing daily reports.',
  },
  {
    step: '06',
    icon: CheckCircle,
    title: 'Clearance report delivered',
    description: 'At job completion, a final clearance report confirms all materials are at pre-loss moisture levels — the insurer\'s sign-off document.',
  },
];

// ---------------------------------------------------------------------------
// What gets documented
// ---------------------------------------------------------------------------

const DOCUMENTATION_ITEMS = [
  { label: 'Moisture mapping', detail: 'Calibrated readings across all affected surfaces — floors, walls, ceilings' },
  { label: 'Photographic record', detail: 'Time-stamped before/during/after photos from every angle' },
  { label: 'Scope of works', detail: 'IICRC-standard itemised description of all required remediation' },
  { label: 'Equipment log', detail: 'Records of dehumidifier and air mover placement, settings, and hours' },
  { label: 'Daily drying reports', detail: 'Progress tracking showing moisture reduction over the drying period' },
  { label: 'Contamination classification', detail: 'IICRC Category 1/2/3 water classification with evidence' },
  { label: 'Materials assessment', detail: 'Itemised list of affected materials — condition, salvageable vs replacement' },
  { label: 'Final clearance report', detail: 'Confirmation that all materials have returned to pre-loss moisture content' },
];

// ---------------------------------------------------------------------------
// Why it matters stats
// ---------------------------------------------------------------------------

const STATS = [
  { value: '100%', label: 'of NRPG jobs documented with RestoreAssist' },
  { value: '48hr', label: 'typical insurer report turnaround' },
  { value: '0', label: 'separate documentation requests from your insurer' },
  { value: 'All', label: 'major Australian insurers accept RestoreAssist reports' },
];

export default function RestoreAssistPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#f9fafb]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify([SERVICE_SCHEMA, BREADCRUMB_SCHEMA, FAQ_SCHEMA]) }}
      />

      <Header />

      <main>
        {/* Hero */}
        <section className="container mx-auto px-4 sm:px-6 py-14 md:py-20 max-w-5xl">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#0d9488]/10 border border-[#0d9488]/30 rounded-sm text-[#0d9488] text-xs font-semibold uppercase tracking-wide mb-6">
                <Shield className="h-3.5 w-3.5" aria-hidden="true" />
                NRPG Field Technology
              </div>

              <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold leading-tight mb-5">
                The documentation that gets{' '}
                <span className="text-[#0d9488]">your claim approved.</span>
              </h1>

              <p className="text-[#9ca3af] text-lg mb-6 leading-relaxed">
                Every NRPG contractor uses RestoreAssist on-site — generating real-time inspection reports, moisture mapping, and scope of works the moment they arrive at your property.
              </p>

              <p className="text-[#9ca3af] text-base mb-8 leading-relaxed">
                This isn&apos;t paperwork filed later. It&apos;s professional field documentation captured at the source — giving your insurer exactly what they need to process your claim without delays or disputes.
              </p>

              <div className="flex flex-wrap gap-3">
                <Link
                  href="/get-started"
                  className="inline-flex items-center gap-2 bg-[#0d9488] hover:bg-[#0f766e] text-white font-semibold px-6 py-3 rounded-sm text-sm transition-colors"
                >
                  Request Emergency Assessment <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
                <a
                  href="https://restoreassist.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 border border-[#374151] text-[#9ca3af] hover:text-[#f9fafb] hover:border-[#6b7280] px-6 py-3 rounded-sm text-sm transition-colors"
                >
                  Visit RestoreAssist.app →
                </a>
              </div>
            </div>

            {/* Right: Stats */}
            <div className="grid grid-cols-2 gap-4">
              {STATS.map((stat) => (
                <div
                  key={stat.label}
                  className="bg-[#0f1115] border border-[#374151] rounded-sm p-5 text-center"
                >
                  <div className="text-3xl font-black text-[#0d9488] mb-2">{stat.value}</div>
                  <div className="text-xs text-[#9ca3af] leading-relaxed">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* What is RestoreAssist */}
        <section className="bg-[#0f1115] border-y border-[#1f2937] py-14">
          <div className="container mx-auto px-4 sm:px-6 max-w-4xl">
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <h2 className="text-2xl font-bold text-white mb-4">
                  What is RestoreAssist?
                </h2>
                <p className="text-[#9ca3af] text-sm leading-relaxed mb-4">
                  RestoreAssist is the professional on-site inspection, reporting, and scoping system used exclusively by NRPG contractors in the field. It runs on contractor devices during every job — capturing moisture readings, photos, equipment data, and site observations in real time.
                </p>
                <p className="text-[#9ca3af] text-sm leading-relaxed mb-4">
                  The output is a structured, IICRC-standard documentation package that insurers recognise and accept — covering everything from initial damage assessment through to final drying clearance.
                </p>
                <p className="text-[#9ca3af] text-sm leading-relaxed">
                  RestoreAssist is a separate product operated at{' '}
                  <a
                    href="https://restoreassist.app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[#0d9488] hover:underline"
                  >
                    restoreassist.app
                  </a>
                  {' '}— but its outputs are integral to every NRPG job delivered through Disaster Recovery Australia.
                </p>
              </div>

              <div className="bg-[#050505] border border-[#1f2937] rounded-sm p-5">
                <p className="text-xs font-semibold text-[#d1d5db] uppercase tracking-wide mb-4">
                  The three-system approach
                </p>
                <div className="space-y-4">
                  {[
                    {
                      brand: 'Disaster Recovery Australia',
                      role: 'Client-facing platform',
                      description: 'You find us after a disaster. You submit a claim. We dispatch the right contractor.',
                      accent: '#0d9488',
                      current: true,
                    },
                    {
                      brand: 'NRPG',
                      role: 'Vetted contractor network',
                      description: 'Australia and New Zealand\'s specialised professional restorers — certified, vetted, insured.',
                      accent: '#0d9488',
                      current: false,
                    },
                    {
                      brand: 'RestoreAssist',
                      role: 'Field documentation system',
                      description: 'On-site inspection, reporting, and scoping used by every NRPG contractor on every job.',
                      accent: '#0d9488',
                      current: false,
                    },
                  ].map((item, i) => (
                    <div key={item.brand} className="flex items-start gap-3">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-[#0d9488]/20 border border-[#0d9488]/40 flex items-center justify-center text-[#0d9488] text-xs font-bold">
                        {i + 1}
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-xs font-bold text-white">{item.brand}</span>
                          {item.current && (
                            <span className="text-[10px] text-[#0d9488] bg-[#0d9488]/10 border border-[#0d9488]/30 px-1.5 py-0.5 rounded-sm">
                              you are here
                            </span>
                          )}
                        </div>
                        <p className="text-[10px] text-[#6b7280] font-medium uppercase tracking-wide mb-0.5">{item.role}</p>
                        <p className="text-xs text-[#9ca3af]">{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* How it works */}
        <section className="container mx-auto px-4 sm:px-6 py-14 max-w-4xl">
          <h2 className="text-2xl font-bold text-white mb-2">
            From claim to clearance report
          </h2>
          <p className="text-[#9ca3af] text-sm mb-8">
            RestoreAssist documentation is produced at every stage of your restoration job.
          </p>

          <div className="space-y-4">
            {HOW_IT_WORKS.map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.step} className="flex items-start gap-4 bg-[#0f1115] border border-[#1f2937] rounded-sm p-5">
                  <div className="flex-shrink-0 w-8 h-8 rounded-sm bg-[#0d9488]/15 border border-[#0d9488]/30 flex items-center justify-center">
                    <Icon className="h-4 w-4 text-[#0d9488]" aria-hidden="true" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-1">
                      <span className="text-[10px] font-bold text-[#0d9488] uppercase tracking-widest">{item.step}</span>
                      <h3 className="text-sm font-semibold text-white">{item.title}</h3>
                    </div>
                    <p className="text-xs text-[#9ca3af] leading-relaxed">{item.description}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* What gets documented */}
        <section className="bg-[#0f1115] border-y border-[#1f2937] py-14">
          <div className="container mx-auto px-4 sm:px-6 max-w-4xl">
            <h2 className="text-2xl font-bold text-white mb-2">
              What RestoreAssist documents on every job
            </h2>
            <p className="text-[#9ca3af] text-sm mb-8">
              Every item below is captured on-site and included in the documentation package delivered to your insurer.
            </p>

            <div className="grid sm:grid-cols-2 gap-3">
              {DOCUMENTATION_ITEMS.map((item) => (
                <div
                  key={item.label}
                  className="flex items-start gap-3 bg-[#050505] border border-[#1f2937] rounded-sm p-4"
                >
                  <CheckCircle className="h-4 w-4 text-[#0d9488] flex-shrink-0 mt-0.5" aria-hidden="true" />
                  <div>
                    <p className="text-sm font-semibold text-white mb-0.5">{item.label}</p>
                    <p className="text-xs text-[#6b7280]">{item.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Why documentation matters */}
        <section className="container mx-auto px-4 sm:px-6 py-14 max-w-4xl">
          <h2 className="text-2xl font-bold text-white mb-6">
            Why professional documentation matters for your claim
          </h2>

          <div className="grid md:grid-cols-3 gap-4 mb-8">
            {[
              {
                title: 'Faster claim approval',
                body: 'Insurers process claims faster when they receive a complete, professional documentation package upfront. No back-and-forth requesting missing information.',
              },
              {
                title: 'Reduces disputes',
                body: 'Objective moisture readings and IICRC-standard scope of works leave little room for an insurer to dispute the extent of damage or the remediation required.',
              },
              {
                title: 'Supports full entitlement',
                body: 'Comprehensive documentation ensures you receive your full policy entitlement — not just what a loss adjuster estimates without field evidence.',
              },
            ].map((card) => (
              <div key={card.title} className="bg-[#0f1115] border border-[#374151] rounded-sm p-5">
                <CheckCircle className="h-5 w-5 text-[#0d9488] mb-3" aria-hidden="true" />
                <h3 className="text-sm font-bold text-white mb-2">{card.title}</h3>
                <p className="text-xs text-[#9ca3af] leading-relaxed">{card.body}</p>
              </div>
            ))}
          </div>

          <div className="bg-[#0d9488]/10 border border-[#0d9488]/30 rounded-sm p-6">
            <div className="flex items-start gap-3">
              <Shield className="h-5 w-5 text-[#0d9488] flex-shrink-0 mt-0.5" aria-hidden="true" />
              <div>
                <p className="text-sm font-semibold text-white mb-1">
                  Accepted by all major Australian insurers
                </p>
                <p className="text-xs text-[#9ca3af]">
                  RestoreAssist documentation is generated to IICRC standards — the professional benchmark recognised by NRMA, Suncorp, Allianz, QBE, RACQ, IAG, and all other major Australian home insurers. NRPG contractors are approved by all major insurers as preferred restoration providers.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="bg-[#0f1115] border-y border-[#1f2937] py-12">
          <div className="container mx-auto px-4 sm:px-6 max-w-3xl">
            <h2 className="text-2xl font-bold text-white mb-6">Questions about RestoreAssist</h2>
            <div className="space-y-4">
              {[
                {
                  q: 'What is RestoreAssist?',
                  a: 'RestoreAssist is the professional on-site inspection, reporting, and scoping system used by all NRPG contractors. It generates real-time moisture maps, photographic records, and insurance-standard scope of works documents during every disaster restoration job.',
                },
                {
                  q: 'How does RestoreAssist help with my insurance claim?',
                  a: 'RestoreAssist produces the professional documentation your insurer needs to assess and approve your claim — including moisture readings, before-and-after photos, equipment logs, and a formal scope of works. This documentation is generated on-site and submitted directly to your insurer, eliminating delays and disputes.',
                },
                {
                  q: 'Do I need to pay extra for RestoreAssist documentation?',
                  a: 'No. RestoreAssist documentation is included as a standard part of every NRPG job. It is not an optional extra — every NRPG contractor is required to use RestoreAssist on every job.',
                },
                {
                  q: 'Can I access my RestoreAssist job report?',
                  a: 'Yes. Your NRPG contractor provides you with a copy of all RestoreAssist documentation produced during your job — including the final clearance report. This documentation is yours to keep and submit to your insurer.',
                },
              ].map((item) => (
                <div key={item.q} className="bg-[#050505] border border-[#1f2937] rounded-sm p-5">
                  <h3 className="text-sm font-semibold text-white mb-2">{item.q}</h3>
                  <p className="text-sm text-[#9ca3af]">{item.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="container mx-auto px-4 sm:px-6 py-14 max-w-3xl text-center">
          <h2 className="text-2xl font-bold text-white mb-3">
            Get the documentation advantage working for you
          </h2>
          <p className="text-[#9ca3af] text-sm mb-6 max-w-xl mx-auto">
            Submit your claim through Disaster Recovery Australia and every NRPG contractor we dispatch will automatically document your damage with RestoreAssist — giving your insurer exactly what they need.
          </p>
          <Link
            href="/get-started"
            className="inline-flex items-center gap-2 bg-[#0d9488] hover:bg-[#0f766e] text-white font-semibold px-8 py-3 rounded-sm text-sm transition-colors"
          >
            Request Emergency Assessment <ArrowRight className="h-4 w-4" aria-hidden="true" />
          </Link>

          {/* Internal links */}
          <div className="mt-8 pt-6 border-t border-[#1f2937] flex flex-wrap gap-2 justify-center">
            {[
              { href: '/how-it-works', label: 'How It Works' },
              { href: '/services/water-damage', label: 'Water Damage' },
              { href: '/faq', label: 'FAQ' },
              { href: '/nrpg', label: 'About NRPG' },
            ].map(({ href, label }) => (
              <Link
                key={href}
                href={href}
                className="text-xs text-[#0d9488] border border-[#0d9488]/30 px-3 py-1.5 rounded-sm hover:bg-[#0d9488]/10 transition-colors"
              >
                {label} →
              </Link>
            ))}
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
