/**
 * Advanced TypeScript Types - Central Export
 *
 * Re-exports all advanced type utilities for easy importing
 */

// Branded Types
export type {
  Brand,
  ServiceId,
  ServiceSlug,
  ServiceCategory,
  LocationId,
  LocationSlug,
  Postcode,
  Latitude,
  Longitude,
  PhoneNumber,
  EmailAddress,
  ABN,
  UserId,
  SessionId,
  ContractorId,
  PageId,
  TemplateId,
  ContentBlockId,
  Currency,
  Percentage,
  Timestamp,
  ISO8601String,
  UnixTimestamp,
  URL,
  ImageURL,
  CanonicalURL,
  Unbrand,
} from './branded';

// Branded type constructors and utilities (value exports)
export { isBrandedType } from './branded';

// Namespace exports to avoid conflicts
export * as BrandedTypes from './branded';

// Type Guards
export type {
  ServiceData,
  LocationData,
  ContactInfo,
  APISuccess,
  APIError,
  APIResponse,
  ValidationResult,
} from './guards';

export {
  isString,
  isNumber,
  isBoolean,
  isNull,
  isUndefined,
  isNullish,
  isNonNullable,
  isObject,
  isArray,
  isDate,
  isError,
  isArrayOf,
  isRecordOf,
  assertString,
  assertNumber,
  assertNonNullable,
  assertArray,
  assertObject,
  isServiceData,
  isLocationData,
  isContactInfo,
  isAPISuccess,
  isAPIError,
  assertNever,
  isDefined,
  isNotNull,
  hasProperty,
  hasOwnProperty,
  isOfType,
  matchType,
  isValidationSuccess,
  isValidationError,
  parseJSON,
  parseNumber,
} from './guards';

// Utility Types
export type {
  DeepPartial,
  DeepReadonly,
  DeepRequired,
  Mutable,
  DeepMutable,
  Nullable,
  Optional,
  NonNullableKeys,
  NullableKeys,
  PickByType,
  OmitByType,
  RequiredKeys,
  OptionalKeys,
  PickRequired,
  PickOptional,
  Exact,
  ValueOf,
  Entries,
  UnionToIntersection,
  UnionToTuple,
  PromiseType,
  ArrayElement,
  FunctionArgs,
  FunctionReturn,
  Constructor,
  AbstractConstructor,
  Merge,
  DeepMerge,
  Overwrite,
  StringKeys,
  NumberKeys,
  SymbolKeys,
  Flatten,
  DeepFlatten,
  NonEmptyArray,
  AtLeastOne,
  ExactlyOne,
  Primitive,
  Falsy,
  JSONValue,
  JSONArray,
  JSONObject,
  Pretty,
  IfEquals,
  WritableKeys,
  ReadonlyKeys,
  PartialBy,
  RequiredBy,
  Awaited,
  DeepAwaited,
} from './utils';

// API Types
export type {
  HTTPMethod,
  APIStatus,
  APIResponse as APIResponseType,
  APISuccessResponse,
  APIErrorResponse,
  APIPendingResponse,
  ErrorCode,
  PaginatedResponse,
  PaginationParams,
  FilterParams,
  SearchParams,
  RequestConfig,
  ServiceRequest,
  ServiceResponse,
  EmergencyRequest,
  EmergencyResponse,
  QuoteRequest,
  QuoteResponse,
  RequestByMethod,
  ResponseByStatus,
  EndpointConfig,
  TypedAPIClient,
  WebhookEvent,
  EmergencyCreatedEvent,
  EmergencyUpdatedEvent,
  QuoteReadyEvent,
  JobCompletedEvent,
  RetryPolicy,
  APIClientState,
  Repository,
  QueryBuilder,
  ComparisonOperator,
  BatchRequest,
  BatchResponse,
  CacheStrategy,
  RateLimitInfo,
  APIMetadata,
} from './api';

export { typedFetch } from './api';

// State Management Types
export type {
  LoadingState,
  AsyncState,
  FormState,
  FormErrors,
  FieldState,
  ValidationRule,
  RequiredRule,
  MinLengthRule,
  MaxLengthRule,
  PatternRule,
  CustomRule,
  Action,
  Reducer,
  Store,
  Middleware,
  Selector,
  MemoizedSelector,
  ContextState,
  ModalState,
  ModalOptions,
  NotificationState,
  ThemeMode,
  ThemeState,
  AuthState,
  PaginationState,
  FilterState,
  SortState,
  TableState,
  WizardState,
  UploadState,
  WebSocketState,
  CacheState,
  OptimisticUpdate,
  UndoRedoState,
  FeatureFlags,
  ABTestState,
  GeolocationState,
  DeviceState,
  ScrollState,
  MediaQueryState,
  IntersectionState,
} from './state';

// Route Types
export type {
  ServiceSlug as RouteServiceSlug,
  ServiceRoute,
  LocationSlug as RouteLocationSlug,
  LocationRoute,
  EmergencyRoute,
  InsuranceProvider,
  InsuranceRoute,
  FAQSlug,
  FAQRoute,
  ValidRoute,
  RouteParams,
  RouteMetadata,
  RouteConfig,
  NavigationItem,
  BreadcrumbItem,
  QueryParams,
  URLBuilder,
  RoutePattern,
  ExtractRouteParams,
  DynamicRoute,
  RouteGuard,
  RouteMiddleware,
  LocationServiceRoute,
  SitemapEntry,
} from './routes';

export { RouteBuilder, buildURL, Routes, isValidRoute } from './routes';
